### PR TITLE
Fix for Julia v1.9 by adding check_belongs_to_model

### LINKED ISSUE #315: Test failure on Julia 1.9
Trying to debug https://github.com/jump-dev/JuMP.jl/pull/3350#issuecomment-1542915469, using my printing PR here: https://github.com/infiniteopt/InfiniteOpt.jl/pull/314.

But I'm going crazy.

I've edited the code in `point_variables.jl` to print what's happening:

image

When the function is called. No error is thrown. When you eval in the REPL, an error is thrown. Ideas???

```Julia
julia> using Test

julia> using InfiniteOpt

julia> m1 = InfiniteModel()
An InfiniteOpt Model
Feasibility problem with:
Finite Parameters: 0
Infinite Parameters: 0
Variables: 0
Derivatives: 0
Measures: 0
Optimizer model backend information: 
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @infinite_parameter(m1, p in [0, 1])
p

julia> @variable(m1, x, Infinite(p))
x(p)

julia> v = build_variable(
           error, 
           VariableInfo(false, 0.0, false, 0.0, false, 0.0, false, 0.0, false, false), 
           Point(x, 0.5),
       )
PointVariable{GeneralVariableRef}(VariableInfo{Float64, Float64, Float64, Float64}(false, 0.0, false, 0.0, false, 0.0, false, 0.0, false, false), x(p), [0.5])

julia> m2 = InfiniteModel()
An InfiniteOpt Model
Feasibility problem with:
Finite Parameters: 0
Infinite Parameters: 0
Variables: 0
Derivatives: 0
Measures: 0
Optimizer model backend information: 
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> JuMP.add_variable(m2, v)
[ Info: Called here
[ Info: x(p)
#= /Users/oscar/.julia/dev/InfiniteOpt/src/point_variables.jl:436 =# InteractiveUtils.@which(JuMP.check_belongs_to_model(divref, model)) = check_belongs_to_model(v::AbstractVariableRef, model::AbstractModel) @ JuMP ~/.julia/packages/JuMP/jYny8/src/variables.jl:280
[ Info: Passed check
x(0.5)

julia> ivref = v.infinite_variable_ref
x(p)

julia> divref = dispatch_variable_ref(ivref)
x(p)

julia> @info divref
[ Info: x(p)

julia> @show InteractiveUtils.@which JuMP.check_belongs_to_model(divref, m2)
#= REPL[85]:1 =# InteractiveUtils.@which(JuMP.check_belongs_to_model(divref, m2)) = check_belongs_to_model(v::AbstractVariableRef, model::AbstractModel) @ JuMP ~/.julia/packages/JuMP/jYny8/src/variables.jl:280
check_belongs_to_model(v::AbstractVariableRef, model::AbstractModel)
     @ JuMP ~/.julia/packages/JuMP/jYny8/src/variables.jl:280

julia> JuMP.check_belongs_to_model(divref, m2)
ERROR: VariableNotOwned{InfiniteVariableRef}(x(p))
Stacktrace:
 [1] check_belongs_to_model(v::InfiniteVariableRef, model::InfiniteModel)
   @ JuMP ~/.julia/packages/JuMP/jYny8/src/variables.jl:282
 [2] top-level scope
   @ REPL[86]:1

(InfiniteOpt) pkg> st
Project InfiniteOpt v0.5.7
Status `~/.julia/dev/InfiniteOpt/Project.toml`
  [1520ce14] AbstractTrees v0.4.4
  [864edb3b] DataStructures v0.18.13
  [31c24e10] Distributions v0.25.90
  [442a2c76] FastGaussQuadrature v0.5.1
  [4076af6c] JuMP v1.11.0 `https://github.com/jump-dev/JuMP.jl.git#master`
  [1d6d02ad] LeftChildRightSiblingTrees v0.2.0
  [d8a4904e] MutableArithmetics v1.3.0
  [189a3867] Reexport v1.2.2
  [276daf66] SpecialFunctions v2.2.0
  [b77e0a4c] InteractiveUtils
  [37e2e46d] LinearAlgebra
```

### PR DESCRIPTION
**Pull request by odow**
Closes #315 

I've very confused as to why this is needed...

### CODE REVIEW

**Comment by pulsipher** [comment]
We'll see what happens with the tests. Super weird that this is needed and even weirder if it works. Maybe some bug in the Julia compiler?

**Comment by odow** [comment]
> Maybe some bug in the Julia compiler?

Yeah. It feels like an issue with precompilation. Here's my current minimal reproducer:

```julia
(base) oscar@Oscars-MBP /tmp % julia +1.9 --project=ifo
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0 (2023-05-07)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(ifo) pkg> st
Status `/private/tmp/ifo/Project.toml`
  [20393b10] InfiniteOpt v0.5.7

julia> versioninfo()
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 8 × Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores

julia> using InfiniteOpt

julia> function my_add_variable(model, v)
           y = InfiniteOpt.dispatch_variable_ref(v.infinite_variable_ref)
           JuMP.check_belongs_to_model(y, model)
           return
       end
my_add_variable (generic function with 1 method)

julia> m1 = InfiniteOpt.InfiniteModel();

julia> InfiniteOpt.@infinite_parameter(m1, p in [0, 1]);

julia> InfiniteOpt.@variable(m1, x, Infinite(p));

julia> v = JuMP.build_variable(
           error, 
           JuMP.VariableInfo(false, 0.0, false, 0.0, false, 0.0, false, 0.0, false, false), 
           InfiniteOpt.Point(x, 0.5),
       );

julia> m2 = InfiniteOpt.InfiniteModel();

julia> my_add_variable(m2, v)  # When called via a function, does not error

julia> y = dispatch_variable_ref(v.infinite_variable_ref)
x(p)

julia> JuMP.check_belongs_to_model(y, m2)  # When called via REPL, does error
ERROR: VariableNotOwned{InfiniteVariableRef}(x(p))
Stacktrace:
 [1] check_belongs_to_model(v::InfiniteVariableRef, model::InfiniteModel)
   @ JuMP ~/.julia/packages/JuMP/AKvOr/src/variables.jl:282
 [2] top-level scope
   @ REPL[12]:1
```

Am I doing anything stupid? If not, I'll open an issue upstream.

**Comment by pulsipher** [comment]
> Am I doing anything stupid? If not, I'll open an issue upstream.

I think I can simplify this, give me a few minutes to check. Installing Julia 1.9....

**Comment by pulsipher** [comment]
@odow I didn't succeed in getting a simpler case which confuses me even more. So yes, you MWE should be good to go to raise an issue.

**Comment by pulsipher** [comment]
With the latest change, strangely using `DispatchVariableRef` which is a super type of `InfiniteVariableRef` instead of `InfiniteVariableRef`, causes the bug to reappear again...

**Comment by pulsipher** [comment]
Requires #314 for tests to pass.

**Pull request merged**
